#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ap_demos

export IDF_PATH=/opt/esp_sdk/esp-idf

include $(IDF_PATH)/make/project.mk
