/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define CONFIG_TOOLCHAIN_PATH ""
#define CONFIG_TOOLCHAIN_PREFIX ""
#define CONFIG_IOT_CORE_ENABLED 1
#define CONFIG_IOT_EXT_BIND_ENABLED 1
#define CONFIG_IOT_EXT_MODEL_ENABLED 1
#define CONFIG_IOT_EXT_OTA_ENABLED 1
