# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)
### DO NOT edit this file!! ###

CONFIG_TOOLCHAIN_PATH="/opt/toolchain/esp8266/xtensa-lx106-elf/bin/"
CONFIG_TOOLCHAIN_PREFIX="xtensa-lx106-elf-"
CONFIG_ADD_PRIVATE_CFLAGS="-g -Wall -Wno-frame-address -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib"
CONFIG_ADD_PRIVATE_CXXFLAGS=""
CONFIG_ADD_PRIVATE_LINK_CFLAGS=""
CONFIG_ADD_PRIVATE_LINK_CXXFLAGS=""
CONFIG_EZIOT_CORE_ENABLE=y
# CONFIG_EZIOT_CORE_MULTI_TASK is not set
CONFIG_EZIOT_CORE_ACEESS_TASK_STACK_SIZE=5376
CONFIG_EZIOT_CORE_ACEESS_TASK_PRIORITY=5
CONFIG_EZIOT_CORE_MESSAGE_SIZE_MAX=2048
CONFIG_EZIOT_CORE_MESSAGE_NUMBER_MAX=64
CONFIG_EZIOT_CORE_EXTEND_COUNT=1
CONFIG_EZIOT_CORE_EXTEND_COUNT_V3=8
CONFIG_EZIOT_CORE_RISK_CONTROL_CMD_MAX=16
CONFIG_EZIOT_CORE_DEFAULT_PUBLISH_RETRY=2
CONFIG_EZIOT_BASE_ENABLE=y
# CONFIG_EZIOT_HUB_ENABLE is not set
CONFIG_EZIOT_MODEL_ENABLE=y
CONFIG_EZIOT_OTA_ENABLE=y
CONFIG_EZIOT_OTA_TASK_STACK_SIZE=6144
CONFIG_EZIOT_OTA_TASK_PRIORITY=10
CONFIG_EZIOT_SHADOW_ENABLE=y
CONFIG_EZIOT_SHADOW_TASK_PRIORITY=2
CONFIG_EZIOT_SHADOW_STACK_SIZE=3584
CONFIG_EZIOT_SHADOW_FULL_SYNC_RETRY_MAX=3
CONFIG_EZIOT_SHADOW_FULL_SYNC_RETRY_INTERVAL=30
CONFIG_EZIOT_SHADOW_FORCE_FULL_SYNC_INTERVAL=86400
CONFIG_EZIOT_TSL_ENABLE=y
CONFIG_EZIOT_TSL_SHADOW_SUPPORT=y
# CONFIG_EZIOT_TSL_LEGALITY_CHECK_NONE is not set
CONFIG_EZIOT_TSL_LEGALITY_CHECK_WEAK=y
# CONFIG_EZIOT_TSL_LEGALITY_CHECK_STRONG is not set
CONFIG_EZIOT_TSL_DOWNLOAD_TASK_PRIORITY=5
CONFIG_EZIOT_TSL_DOWNLOAD_STACK_SIZE=5020
CONFIG_EZIOT_TSL_PROFILE_MAP_SIZE=4096
CONFIG_EZIOT_TSL_PROFILE_SIZE=8192
CONFIG_EZOS_KV_ENABLE=y
CONFIG_EZOS_LIBC_ENABLE=y
CONFIG_EZOS_MEM_ENABLE=y
CONFIG_EZOS_SOCKET_ENABLE=y
CONFIG_EZOS_SYSTEM_ENABLE=y
CONFIG_EZOS_THREAD_ENABLE=y
CONFIG_EZOS_TIME_ENABLE=y
CONFIG_EZIOT_COMPONENT_FLASHDB_ENABLE=y
CONFIG_EZIOT_COMPONENT_FLASHDB_USING_KVDB=y
# CONFIG_EZIOT_COMPONENT_FLASHDB_KV_AUTO_UPDATE is not set
# CONFIG_EZIOT_COMPONENT_FLASHDB_USING_TSDB is not set
# CONFIG_EZIOT_COMPONENT_FLASHDB_USING_FILE_LIBC_MODE is not set
# CONFIG_EZIOT_COMPONENT_FLASHDB_USING_FILE_POSIX_MODE is not set
CONFIG_EZIOT_COMPONENT_FLASHDB_USING_FAL_MODE=y
CONFIG_EZIOT_COMPONENT_FLASHDB_WRITE_GRAN_1BIT=y
# CONFIG_EZIOT_COMPONENT_FLASHDB_WRITE_GRAN_8BIT is not set
# CONFIG_EZIOT_COMPONENT_FLASHDB_WRITE_GRAN_32BIT is not set
# CONFIG_EZIOT_COMPONENT_FLASHDB_BIG_ENDIAN is not set
CONFIG_EZIOT_COMPONENT_FLASHDB_DEBUG_ENABLE=y
CONFIG_EZIOT_COMPONENT_CJSON_ENABLE=y
# CONFIG_EZIOT_COMPONENT_CLI_ENABLE is not set
CONFIG_EZIOT_COMPONENT_EZCONN_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZCONN_HTTPD_STACK_SIZE=8192
CONFIG_EZIOT_COMPONENT_EZLIST_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZLOG_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZLOG_OUTPUT_ENABLE=y
# CONFIG_EZIOT_COMPONENT_EZLOG_ASSERT_ENABLE is not set
CONFIG_EZIOT_COMPONENT_EZLOG_LINE_BUF_SIZE=1024
CONFIG_EZIOT_COMPONENT_EZLOG_LINE_NUM_MAX_LEN=5
CONFIG_EZIOT_COMPONENT_EZLOG_FILTER_TAG_MAX_LEN=16
CONFIG_EZIOT_COMPONENT_EZLOG_FILTER_KW_MAX_LEN=16
CONFIG_EZIOT_COMPONENT_EZLOG_FILTER_TAG_LVL_MAX_NUM=5
CONFIG_EZIOT_COMPONENT_EZLOG_NEWLINE_SIGN_CRLF=y
# CONFIG_EZIOT_COMPONENT_EZLOG_NEWLINE_SIGN_LF is not set
# CONFIG_EZIOT_COMPONENT_EZLOG_NEWLINE_SIGN_CR is not set
CONFIG_EZIOT_COMPONENT_EZLOG_COLOR_ENABLE=y
# CONFIG_EZIOT_COMPONENT_EZLOG_ASYNC_OUTPUT_ENABLE is not set
# CONFIG_EZIOT_COMPONENT_EZLOG_BUF_OUTPUT_ENABLE is not set
CONFIG_EZIOT_COMPONENT_EZTIMER_ENABLE=y
CONFIG_EZIOT_CONPONENT_TIMER_TASK_STACK_SIZE=3072
CONFIG_EZIOT_COMPONENT_EZUTIL_MISC_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZUTIL_S2J_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZUTIL_UUID_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZXML_ENABLE=y
CONFIG_EZIOT_COMPONENT_EZHTTPD_ENABLE=y
CONFIG_EZIOT_COMPONENT_MBEDTLS_ENABLE=y
CONFIG_EZIOT_COMPONENT_MQTT_ENABLE=y
CONFIG_EZIOT_COMPONENT_UTEST_ENABLE=y
CONFIG_EZIOT_COMPONENT_WEBCLIENT_ENABLE=y
CONFIG_EZIOT_UNIT_TEST_ENABLE=y
CONFIG_EZIOT_UNIT_TEST_REPORT_LOGLVL=2
CONFIG_EZIOT_UNIT_TEST_SDK_LOGLVL=-1
CONFIG_EZIOT_UNIT_TEST_CASE_TIEMOUT_SECONDS=10
CONFIG_EZIOT_UNIT_TEST_CLOUD_HOST="devcn.eziot.com"
CONFIG_EZIOT_UNIT_TEST_CLOUD_PORT=8666
# CONFIG_EZIOT_UNIT_TEST_DEV_AUTH_MODE_SAP is not set
CONFIG_EZIOT_UNIT_TEST_DEV_AUTH_MODE_LICENCE=y
CONFIG_EZIOT_UNIT_TEST_DEV_PRODUCT_KEY="4LYV8SK7UKLBOUOVS6HXVX"
CONFIG_EZIOT_UNIT_TEST_DEV_NAME="A532NO6K0Q2O"
CONFIG_EZIOT_UNIT_TEST_DEV_LICENSE="J7Fv5gCsTczVe38aNLe4ev"
CONFIG_EZIOT_UNIT_TEST_DEV_DISPLAY_NAME="IOT_UTEST_DEV"
CONFIG_EZIOT_UNIT_TEST_DEV_FIRMWARE_VERSION="V1.2.0 build 201212"
CONFIG_EZIOT_UNIT_TEST_WIFI_SSID="Lee"
CONFIG_EZIOT_UNIT_TEST_WIFI_PASSWORD="12345678"
# CONFIG_EZIOT_EXAMPLES_ENABLE is not set
CONFIG_ADD_EZOS_INC_DIRS=/home/xurongjun/git/ez_iot_os/components/FlashDB/inc /home/xurongjun/git/ez_iot_os/components/FlashDB/port/fal/inc /home/xurongjun/git/ez_iot_os/components/cJSON/inc /home/xurongjun/git/ez_iot_os/components/ezconn/inc /home/xurongjun/git/ez_iot_os/components/ezlist/inc /home/xurongjun/git/ez_iot_os/components/ezlog/inc /home/xurongjun/git/ez_iot_os/components/eztimer/inc /home/xurongjun/git/ez_iot_os/components/ezutil/misc/inc /home/xurongjun/git/ez_iot_os/components/ezutil/s2j/inc /home/xurongjun/git/ez_iot_os/components/ezutil/uuid/inc /home/xurongjun/git/ez_iot_os/components/ezxml/inc /home/xurongjun/git/ez_iot_os/components/http_server/inc /home/xurongjun/git/ez_iot_os/components/mbedtls/include /home/xurongjun/git/ez_iot_os/components/mqtt/inc /home/xurongjun/git/ez_iot_os/components/utest/inc /home/xurongjun/git/ez_iot_os/components/webclient/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_bm/base/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_bm/model/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_bm/ota/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_bm/shadow/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_bm/tsl/inc /home/xurongjun/git/ez_iot_os/eziot/ez_iot_core/inc /home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/main /home/xurongjun/git/ez_iot_os/platform/inc
CONFIG_ADD_EZOS_LIB_DIRS=-L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/FlashDB -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/cJSON -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezconn -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezlist -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezlog -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/eztimer -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezutil -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezxml -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/http_server -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/mbedtls -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/mqtt -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/utest -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/webclient -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ez_iot_bm -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ez_iot_core -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/main -L/home/xurongjun/git/ez_iot_os/apps/ezapp_bulb/port/esp8266/build/ezos
CONFIG_ADD_EZOS_LIB_DEPENS=-lFlashDB -lcJSON -lezconn -lezlist -lezlog -leztimer -lezutil -lezxml -lhttp_server -lmbedtls -lmqtt -lutest -lwebclient -lez_iot_bm -lez_iot_core -lmain -lezos
