#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

export IDF_PATH=/opt/esp_sdk/ESP8266_RTOS_SDK

PROJECT_NAME := flashDB_demo

include $(IDF_PATH)/make/project.mk

